# Generated by Django 4.1.6 on 2023-02-14 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_listing_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='users_watching',
            field=models.ManyToManyField(blank=True, related_name='listings_watched', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings_owned', to=settings.AUTH_USER_MODEL),
        ),
    ]
