# Generated by Django 4.1.6 on 2023-02-20 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_listing_users_watching_alter_listing_listed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bidded_by',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL),
        ),
    ]
