# Generated by Django 4.1.6 on 2023-02-20 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_bid_bidded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bidded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL),
        ),
    ]
