# Generated by Django 4.1.6 on 2023-02-20 20:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_bid_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 20, 17, 14, 28, 499812)),
        ),
        migrations.AlterField(
            model_name='bid',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 20, 17, 14, 28, 499812)),
        ),
    ]
